[package]
name = "sys-mon-dash"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30"
tokio = { version = "1", features = ["full"] }
axum = "0.7"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower = "0.5"